// <auto-generated />
using Cofy.IncomeTaxCalculator.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cofy.IncomeTaxCalculator.Data.Migrations
{
    [DbContext(typeof(TaxCalculatorDbContext))]
    [Migration("20250306122547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cofy.IncomeTaxCalculator.Domain.Entities.TaxBandEntity", b =>
                {
                    b.Property<int>("Min")
                        .HasColumnType("int");

                    b.Property<int>("Max")
                        .HasColumnType("int");

                    b.Property<byte>("Percent")
                        .HasColumnType("tinyint");

                    b.HasKey("Min", "Max", "Percent");

                    b.HasIndex("Min", "Max", "Percent")
                        .IsUnique();

                    b.ToTable("TaxBands", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
